/*
 * File: sigint_handler_example.c
 * Description:
 *   Demonstrates how to handle the SIGINT signal using the `signal()` system call in C.
 *   The SIGINT signal is typically sent when the user presses Ctrl+C in the terminal.
 *
 * Functionality:
 *   - The program sets a custom signal handler `ctrl_c()` for the SIGINT signal.
 *   - It enters an infinite loop where it prints the process ID (PID) every 2 seconds.
 *   - When the user presses Ctrl+C, the custom handler is executed and prints "hello".
 *
 * How to Use:
 *   1. Compile the program:
 *      gcc sigint_handler_example.c -o sigint_handler_example
 *
 *   2. Run the program:
 *      ./sigint_handler_example
 *
 *   3. Press `Ctrl+C` to trigger the signal and see the custom message "hello".
 *
 * Sample Output:
 *   12345
 *   12345
 *   12345
 *   hello
 *   12345
 *   ...
 *
 * Notes:
 *   - The `signal()` function installs a signal handler for the specified signal.
 *   - `SIGINT` is the interrupt signal generated by the terminal when `Ctrl+C` is pressed.
 *   - This program demonstrates basic asynchronous signal handling in a running process.
 *
 * Author: Monish Kumar
 */

#include <stdio.h>
#include <signal.h>
#include <unistd.h>

void ctrl_c()
{
  printf("hello");
}

int main() 
{
  signal(SIGINT, ctrl_c);

  while(1)
  {
    printf("%d\n",getpid());
    sleep(2);
  }
}
